### ISSUE TITLE
How I integrate AirNotifier with Moodle.

### ISSUE THREAD

**Issue by echarif** [airnotifier/airnotifier#106]
I need help to implement Airnotifier with moodle, I followed all steps in moodle.org and airnotifier, but doesn't work.

thanks in advance!!

**Comment by snehaldpatel1992** [comment]
Hey echarif,  If you found any success integrating Moodle with Air notifier, Can you help me with that? It is strange that air notifier is so much powerful tool but still we need Moodle and there is no proper documentation available.

**Comment by echarif** [comment]
Hi snehaldpatel1992!!

I elaborated a good document to implement Push notifications in Moodle with Airnotifier, but it's wrote in spanish.

**Comment by vmusica** [comment]
Hey echarif, I could use Your documentation as well, spanish isn't an issue (a t least for my co-workers).

**Comment by arandilopez** [comment]
@echarif Can you mail me that paper please, it will help me a lot

**Comment by yencavivas** [comment]
Hi echarif! Please, mail can give me your document, it would help me a lot. Thanks a lot!!

**Comment by frankiekam** [comment]
Hi echarif. Please email me the Spanish document as well. I am having problems integrating Airnotifier with Moodle too. My email address is: boonsengkam dot gmail.com

**Comment by jeremycod** [comment]
Hi @echarif. Could you email me that document please?
My email address is: zoran.jeremic at gmail.com
Thanks

**Comment by nachoan** [comment]
Hi Echarif,
Could yoy email me the Spanish Documentatio please?
My email is nachoan@lasalle.es. Thanks

Saludos,
Podrías mandarnos una copia de la documentación en castellano por favor? Gracias

**Comment by srinathvsp** [comment]
hi can u mail me moodle integration document     srinathvsp1986p@gmail.com
thank in advance

**Comment by mohitsofat** [comment]
Hi @echarif Could you email me the Spanish Documentation please?
My email is mohitsofat@gmail.com
 Thanks

**Comment by ptoptsis** [comment]
Hi, I am also trying to integrate moodle with airnotifier with no luck. Could you please email me the document described above. Thanks
My mail is ptoptsis@gmail.com

**Comment by blazing1987** [comment]
Hello @echarif ,

I am facing lot of issues due to no documentation. I do not intend to setup a server right now but will be using airnotifier services for now.
We want to setup a server sometime later, so a documentation covering both is much needed. Could you mail me your documentation?  

Thanks in advance.

**Comment by blazing1987** [comment]
Hello @echarif ,

I am facing lot of issues due to no documentation. I do not intend to setup a server right now but will be using airnotifier services for now.
We want to setup a server sometime later, so a documentation covering both is much needed. Could you mail me your documentation? My mail id is vikram dot baghel at gmail dot com.

Thanks in advance.

**Comment by rec16005** [comment]
Hello @echarif can you mail me the documentation please? sebasr9710@gmail.com
