### ISSUE TITLE
airnotifier not working

### ISSUE THREAD

**Issue by a1pro** [airnotifier/airnotifier#137]
Hey,
i have install airnotifier from git. but its not working.
if i''m using my localhost or live server using http://domain-name:27017 or http://domain-name:8801
nothing to open, only error show (web page not available).
please give me a solution.
king regards.

**Comment by dcai** [comment]
hi @a1pro I need more than "not working" to help you, do you have any error messages?

**Comment by jakubTraveler** [comment]
Hi. I might had the same issue. At least I guess since according to the information provided.

I'm was not able to start the AirNotifier server..

AirNotifier.log:
Invalid path to SSL certificate and private key

AirNotifier.err:
[I 160317 22:44:33 airnotifier:189] Starting AirNotifier server
Traceback (most recent call last):
  File "airnotifier.py", line 285, in <module>
    AirNotifierApp(services=services).main()
  File "airnotifier.py", line 194, in main
    ssl_ctx.load_cert_chain(options.httpscertfile, options.httpskeyfile)
IOError: [Errno 2] No such file or directory

I was not sure what the problem was. Until.. I read correctly the installation guide..
Then I set **Https** to **False**.
And set the correct path to certificates..
Yes, that was the issue.

Hope that helps someone who will miss the line with the change path text.. :D

**Comment by srinathvsp** [comment]
hi its working fine .but don't set Https to False. its resolved by creating ssl cer and server key following link http://www.thegeekstuff.com/2009/07/linux-apache-mod-ssl-generate-key-csr-crt-file/
and also copy the those file and put it in
httpscertfile = "/path/to/ssl/certificate.cert"
httpskeyfile = "/path/to/ssl/server.key"
then is get resolved
