### ISSUE TITLE
bad handshake: Error SSL routines

### ISSUE THREAD

**Issue by yusufyilmaz** [airnotifier/airnotifier#142]
Hello There,

I have some problems with airnotifier. I have installed moodle branch of airnotifier. Server is running perfectly but does not sending push messages. I tried with android using gcm app id and api key. It is not working when I try "Broadcast" feauture. I also tried using this https://github.com/airnotifier/test-scripts/blob/master/v2/push_gcm.php and I get this error:

`string(121) "{"error": "(\"bad handshake: Error([('SSL routines', 'SSL3_GET_SERVER_CERTIFICATE', 'certificate verify failed')],)\",)"}"`

Does Airnotifier server need SSL certificate? Can it work without SSL certificate? Do you think that using letsencyrpt should be ok?

**Comment by dcai** [comment]
Hi @yusufyilmaz moodle branch is out-dated, have you tried this branch? https://github.com/airnotifier/airnotifier/tree/1.x

**Comment by hitteshahuja** [comment]
@dcai We were getting the same error and we have since upgraded to the 1.x branch as well as using python 2.7.10 but now we effectively get the same error in a slightly better language 

`[I 160331 09:27:09 connectionpool:758] Starting new HTTPS connection (1): android.googleapis.com
[E 160331 09:27:09 airnotifier:154] GCM problem: HTTPSConnectionPool(host='android.googleapis.com', port=443): Max retries exceeded with url: /gcm/send (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7f166f2af790>: Failed to establish a new connection: [Errno -2] Name or service not known',)))
`
We are behind a proxy and have set http_proxy and https_proxy. I am,however, not making use of `use_https=true`
as I dont know where to get the cert and the key from. Would you know how ? 

Thanks

**Comment by yusufyilmaz** [comment]
@dcai I have come up with that Python is checking SSL as default since v2.7.9  Lathough we have a trusted ssl on the server, it stils give the error. I am not sure if the error is caused by our side server ssl or GCM side that is not accepting our sertificate. We have ssl v2 level certificate

**Comment by srinathvsp** [comment]
hey please create ur ssl certificates and server key file by following http://www.thegeekstuff.com/2009/07/linux-apache-mod-ssl-generate-key-csr-crt-file/ and use this link for.
after creation copy those file to /path/to/ssl/certificate.cert  please look into airnotifier.conf
httpscertfile = "/path/to/ssl/certificate.cert"
httpskeyfile = "/path/to/ssl/server.key"

**Comment by yusufyilmaz** [comment]
@srinathvsp I had to disable SSL check on python settings and using non secure method but it is working. Thank you anyway. It is shame that we do not have settings not to use ssl on python new version.

**Comment by gmondo** [comment]
Hello, 

I have a similar problem with CentOS 7 and Python 2.7.10 

SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:765)
[E 160811 08:29:45 web:1908] 500 POST /api/v2/push (10.0.2.2) 135.98ms

I solved it as follows:

diff --git a/pushservices/gcm.py b/pushservices/gcm.py
...
-        response = requests.post(self.endpoint, data=payload, headers=headers)
+        response = requests.post(self.endpoint, data=payload, headers=headers, verify='/etc/pki/tls/certs/ca-bundle.crt')

The good solution could be to add a verify path in airnotifier.conf ...
