### ISSUE TITLE
how to bind airnotifier to ipaddress instead of localhost

### ISSUE THREAD

**Issue by enderulusoy** [airnotifier/airnotifier#162]
Our installation works fine on host itself (we can see a login page from command line with elinks). But we can not bind it to server's real ip address. so could not use it from remote machines. how can we achieve it? thank you.

**Comment by yusufyilmaz** [comment]
Hello @enderulusoy,

Once you install the airnotifier, you will be able to access the airnotifier over server's real ip adress with a default port 8801. [Here](https://github.com/airnotifier/airnotifier/wiki/Installation#set-up-airnotifier) is the example. 

If you want to change the default port, you can set this with conf file ([example conf file](https://github.com/airnotifier/airnotifier/blob/1.x/airnotifier.conf-sample)) However, I strongly suggest that a subdomain you should assign to the airnotifier, instead of ip address.

Best.
